"""Generate the single-file vendorable build.

What this package competes with is copy-paste, so ``curl`` has to be as easy as
``pip``. This concatenates the package into one importable module with the XML
witnesses embedded, so the vendored copy keeps the property that makes the table
trustworthy: it still checks itself against real product metadata.

    python scripts/build_vendored.py            # write geospatial_spec.py
    python scripts/build_vendored.py --check    # fail if it has drifted (CI)

The ``--check`` gate exists because a vendored file that silently lags the
package is worse than no vendored file: it looks maintained and is not.
"""

from __future__ import annotations

import argparse
import base64
import gzip
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PKG = ROOT / "src" / "geospatial_spec"
#: Kept out of the repo root so it cannot shadow the real package on sys.path.
OUT = ROOT / "vendored" / "geospatial_spec.py"

#: Concatenation order: dependencies before dependents.
MODULES = ["exceptions", "_types", "_witness", "_table", "sentinel2", "sentinel1", "common"]

WITNESSES = ["MTD_MSIL2A_N0400.xml", "s1a-iw-grd-vv-annotation.xml"]

HEADER = '''"""geospatial-spec, vendored single-file build. DO NOT EDIT.

Generated by scripts/build_vendored.py from the geospatial-spec package.
Behaviour is identical to the installed package, including the witness checks:
the ESA product metadata this table is verified against is embedded below.

Regenerate rather than edit. To check whether your copy is current, compare
__version__ against the published package.

Contains modified Copernicus Sentinel data 2021-2022. See the project's
PROVENANCE.md for source granules, pruning, and license.
"""

from __future__ import annotations

import base64 as _base64
import gzip as _gzip
import io as _io
import enum as _enum
import json
import sys
from dataclasses import dataclass, field
from datetime import date, datetime
from pathlib import Path
from typing import Any, Callable, Mapping, Protocol, TypeVar
from xml.etree import ElementTree

'''

WITNESS_LOADER = '''

# --------------------------------------------------------------------------
# Embedded witnesses. The vendored build keeps the property that makes this
# table worth trusting: every fact is still checked against real ESA metadata.
# --------------------------------------------------------------------------

_EMBEDDED_WITNESSES: dict[str, str] = {}


def _witness_bytes(name: str) -> bytes:
    """Decompress an embedded witness document."""
    return _gzip.decompress(_base64.b64decode(_EMBEDDED_WITNESSES[name]))


def _parse_embedded(name: str) -> ElementTree.Element:
    return ElementTree.fromstring(_witness_bytes(name))


class _WitnessNamespace:
    """Stands in for the package's ``_witness`` module.

    In the package the fact modules do ``from . import _witness as witness``
    and then call ``witness.text(...)``. Flattened into one file there is no
    submodule to import, so the same name is rebound to this namespace after
    the witness helpers are defined below.
    """


witness = _WitnessNamespace()

'''

WITNESS_BINDING = '''

# Bind the helpers onto the stand-in namespace, so `witness.text(...)` in the
# fact-extraction functions resolves exactly as it does in the package.
witness.text = text
witness.from_json = from_json
witness.from_xml = from_xml
witness.from_mapping = from_mapping

'''


#: Source modules that each define their own private ``_FACTS`` table.
_TABLE_OWNERS = {"sentinel2", "sentinel1", "common"}

_FLAT_API = '''

# --------------------------------------------------------------------------
# Flat public surface for the vendored build.
#
# The package exposes three modules; a single file cannot. Sentinel-2 names
# stay unprefixed because that is what a caller reaches for first. The other
# tables keep an explicit suffix so nothing collides silently.
# --------------------------------------------------------------------------

explain = explain_sentinel2
fact_names = fact_names_sentinel2

s1_pixel_spacing_m = pixel_spacing_m
s1_pixel_value_convention = pixel_value_convention
s1_is_calibrated = is_calibrated
s1_dual_pol_channels = dual_pol_channels
s1_explain = explain_sentinel1

common_explain = explain_common
common_is_interpolating = is_interpolating
common_normalise_epsg = normalise_epsg
common_epsg_equivalent = epsg_equivalent

_FACTS = _FACTS_sentinel2  # the table `explain` reads

__all__ = [
    "boa_offset", "quantification", "to_reflectance",
    "nodata_value", "is_ambiguous_zero", "resample_nodata_policy",
    "assert_nodata_declared", "assert_baseline_consistent",
    "parse_baseline", "baseline_for", "baseline_has_offset",
    "explain", "fact_names",
    "s1_pixel_spacing_m", "s1_pixel_value_convention", "s1_is_calibrated",
    "s1_dual_pol_channels", "s1_explain",
    "common_is_interpolating", "common_normalise_epsg", "common_epsg_equivalent",
    "common_explain",
    "FactTable", "SpecFact", "from_json", "from_xml", "from_mapping",
    "GeospatialSpecError", "ScopeRequired", "BaselineMismatch",
    "NodataUndeclared", "UnknownScope",
    "__version__",
]

__version__ = "0.1.1"
'''


def _rename_global(text: str, old: str, new: str) -> str:
    """Rename a module-level name.

    Skips attribute access (``table.explain(...)``), so renaming the
    module-level ``explain`` function does not also rename
    ``FactTable.explain``, which is a different thing entirely. Module-level
    assignments *are* renamed, since that is where the name is defined.
    """
    return re.sub(rf"(?<![.\w]){re.escape(old)}\b", new, text)


def _strip_module(text: str) -> str:
    """Remove imports that the single file hoists into its own header."""
    out = []
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("from __future__ import"):
            continue
        # Intra-package imports resolve to names already in this file.
        if stripped.startswith("from .") or stripped.startswith("from geospatial_spec"):
            continue
        # Stdlib imports are hoisted; keep the file's own logic only.
        is_import = stripped.startswith(("import ", "from "))
        if is_import and "geospatial_spec" not in stripped:
            if any(
                stripped.startswith(f"import {m}") or stripped.startswith(f"from {m}")
                for m in ("json", "sys", "enum", "base64", "gzip", "io")
            ):
                continue
            hoisted = ("from dataclasses", "from datetime", "from pathlib",
                       "from typing", "from xml", "from collections.abc")
            if stripped.startswith(hoisted):
                continue
        out.append(line)
    return "\n".join(out)


def build() -> str:
    parts = [HEADER]

    # Witness data, embedded and compressed.
    encoded = {}
    for name in WITNESSES:
        raw = (PKG / "_witnesses" / name).read_bytes()
        # mtime=0: gzip stamps the wall clock into its header by default, which
        # makes the generated file differ on every rebuild and fails --check.
        encoded[name] = base64.b64encode(gzip.compress(raw, 9, mtime=0)).decode("ascii")

    parts.append(WITNESS_LOADER)
    for name, blob in encoded.items():
        parts.append(f'_EMBEDDED_WITNESSES[{name!r}] = (\n')
        for i in range(0, len(blob), 76):
            parts.append(f'    "{blob[i : i + 76]}"\n')
        parts.append(")\n\n")

    for module in MODULES:
        source = (PKG / f"{module}.py").read_text()
        parts.append(f"\n# {'=' * 70}\n# {module}.py\n# {'=' * 70}\n\n")
        stripped = _strip_module(source)
        # Each source module owns a private module-level ``_FACTS`` table. In a
        # single file they would all be the same global, so the last one loaded
        # would silently win and every earlier module's facts would vanish.
        # Namespace them per source module, and rename their per-module helpers
        # for the same reason.
        if module in _TABLE_OWNERS:
            for name in ("_FACTS", "explain", "fact_names"):
                stripped = _rename_global(stripped, name, f"{name}_{module}")
        parts.append(stripped)
        parts.append("\n")
        # The fact modules call `witness.text(...)`; bind the helpers onto the
        # stand-in namespace as soon as _witness.py's contents are in scope.
        if module == "_witness":
            parts.append(WITNESS_BINDING)

    body = "".join(parts)

    # Re-expose the flat public API the single-file user expects: sentinel2's
    # names are the unprefixed ones, since that is the module a caller reaches
    # for first; the others stay reachable under an explicit suffix.
    body += _FLAT_API

    # The vendored build reads witnesses from memory, not from disk.
    body = body.replace(
        '_MTD_WITNESS = witness.from_xml(_MTD, _mtd_facts)',
        '_MTD_WITNESS = lambda: _mtd_facts(_parse_embedded("MTD_MSIL2A_N0400.xml"))',
    )
    body = body.replace(
        '_ANNOTATION_WITNESS = witness.from_xml(_ANNOTATION, _annotation_facts)',
        '_ANNOTATION_WITNESS = lambda: _annotation_facts(\n'
        '    _parse_embedded("s1a-iw-grd-vv-annotation.xml")\n'
        ')',
    )
    # `witness.from_json` etc. remain available as module-level functions.
    body = body.replace("witness.from_json", "from_json")
    return body


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if the committed file differs from a fresh build",
    )
    args = parser.parse_args()

    generated = build()

    if args.check:
        if not OUT.exists():
            print(f"{OUT.name} is missing; run scripts/build_vendored.py", file=sys.stderr)
            return 1
        if OUT.read_text() != generated:
            print(
                f"{OUT.name} has drifted from the package source.\n"
                f"Run: python scripts/build_vendored.py",
                file=sys.stderr,
            )
            return 1
        print(f"{OUT.name} is current ({len(generated):,} bytes)")
        return 0

    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text(generated)
    print(f"wrote {OUT.name} ({len(generated):,} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
